import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
// import { Container } from "postcss";
import Container from "../components/container";
const inter = Inter({ subsets: ["latin"] });
// kuch aisa krna h jiska effect saare pages pr rahe, toh use yahan kro
export const metadata: Metadata = {
  title: "Nim-Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-100 text-zinc-900 min-h-screen`}>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
        
        </body>
    </html>
  );
}
